version: 2
jobs:
  build_and_test:
    docker:
    - image: cypress/base:8
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-npm-deps-{{ checksum "package.json" }}
        - v1-npm-deps
    - run:
        name: Install, run and test
        command: |
          npm install
          npm run dev
          npm test
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$APP_NAME.git master

workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
    - build_and_test
    - deploy:
        requires:
          - build_and_test